# Serving HTML through API Gateway for AWS Lambda
service: staffrosterdisplay

frameworkVersion: ">=1.3.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  endpointType: PRIVATE

functions:
  staffrosterdisplay:
    handler: handlers/staffRosterDisplay.displayPage
    events:
      - http:
          method: get
          path: staffrosterdisplay
